name: tfsec scan

on:
  push:
    branches:
      - prod
      - staging
      - dev

jobs:
  tfsec:
    name: tfsec  # This is the status check name
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0

      - name: Report status
        if: ${{ always() }}
        run: echo "::notice ::tfsec scan complete"
